[package]
name = "practice-program-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
reqwest = { version = "0.10.8", features = ["blocking"] }
